version: '2'
networks:
  bone:
    driver: bridge
volumes:
  dataVol: { driver: local }
services:
  nginx:
    ## nginx or openresty 二选一：镜像
    image: nginx:1.9
    volumes:
      - ./docker-compose.d/nginx/conf.d:/etc/nginx/conf.d
      - ./docker-compose.d/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-compose.d/nginx/basic.htpasswd:/etc/nginx/basic.htpasswd
    networks:
      bone:
    ports: ['8088:80']
    restart: always
    environment: []
#  sandbox:
#    build: ./  # 以当前的Dockerfile构建
#    restart: always
#    networks:
#      bone:
#    #dns: ['114.114.114.114', '8.8.8.8']
#    ports: ['51080:8080']
#    volumes:
#      - dataVol:/var/lib/tiddlywiki
#    working_dir: /var/lib/tiddlywiki
#    environment:
#      - TW_WIKIPATH=sandbox
#      - TW_USERNAME=sandboxuser
#      - TW_PASSWORD=sandboxpass


  edu:
    build: ./  # 以当前的Dockerfile构建
    restart: always
    networks:
      bone:
    volumes:
      #- dataVol:/var/lib/tiddlywiki
      - ~/repo/noodle/bd-op/tiddlywikidata:/var/lib/tiddlywiki
      # 打补丁，使得 GET /status 的时候，返回的用户名是basic auth中登录的名字，而不是server命令指定的名字
      - ./docker-compose.d/server.js:/usr/local/lib/node_modules/tiddlywiki/core/modules/commands/server.js
    environment:
      - TW_WIKIPATH=edu
      - TW_USERNAME=anonymous
      - TW_PASSWORD=
      ## double $ to escpae
      - TW_ROOTTIDDLER=$$:/core/save/all

  itt:
    build: ./  # 以当前的Dockerfile构建
    restart: always
    networks:
      bone:
    volumes:
      #- dataVol:/var/lib/tiddlywiki
      - ~/repo/noodle/bd-op/tiddlywikidata:/var/lib/tiddlywiki
      # 打补丁，使得 GET /status 的时候，返回的用户名是basic auth中登录的名字，而不是server命令指定的名字
      - ./docker-compose.d/server.js:/usr/local/lib/node_modules/tiddlywiki/core/modules/commands/server.js
    environment:
      - TW_WIKIPATH=itt
      - TW_USERNAME=anonymous
      - TW_PASSWORD=
      ## double $ to escpae
      - TW_ROOTTIDDLER=$$:/core/save/all

  langs:
    build: ./  # 以当前的Dockerfile构建
    restart: always
    networks:
      bone:
    volumes:
      #- dataVol:/var/lib/tiddlywiki
      - ~/repo/noodle/bd-op/tiddlywikidata:/var/lib/tiddlywiki
      # 打补丁，使得 GET /status 的时候，返回的用户名是basic auth中登录的名字，而不是server命令指定的名字
      - ./docker-compose.d/server.js:/usr/local/lib/node_modules/tiddlywiki/core/modules/commands/server.js
    environment:
      - TW_WIKIPATH=langs
      - TW_USERNAME=anonymous
      - TW_PASSWORD=
      ## double $ to escpae
      - TW_ROOTTIDDLER=$$:/core/save/all

  note:
    build: ./  # 以当前的Dockerfile构建
    restart: always
    networks:
      bone:
    volumes:
      #- dataVol:/var/lib/tiddlywiki
      - ~/repo/noodle/bd-op/tiddlywikidata:/var/lib/tiddlywiki
      # 打补丁，使得 GET /status 的时候，返回的用户名是basic auth中登录的名字，而不是server命令指定的名字
      - ./docker-compose.d/server.js:/usr/local/lib/node_modules/tiddlywiki/core/modules/commands/server.js
    environment:
      - TW_WIKIPATH=note
      - TW_USERNAME=anonymous
      - TW_PASSWORD=
      ## double $ to escpae
      - TW_ROOTTIDDLER=$$:/core/save/all

  sw:
    build: ./  # 以当前的Dockerfile构建
    restart: always
    networks:
      bone:
    volumes:
      #- dataVol:/var/lib/tiddlywiki
      - ~/repo/noodle/bd-op/tiddlywikidata:/var/lib/tiddlywiki
      # 打补丁，使得 GET /status 的时候，返回的用户名是basic auth中登录的名字，而不是server命令指定的名字
      - ./docker-compose.d/server.js:/usr/local/lib/node_modules/tiddlywiki/core/modules/commands/server.js
    environment:
      - TW_WIKIPATH=sw
      - TW_USERNAME=anonymous
      - TW_PASSWORD=
      ## double $ to escpae
      - TW_ROOTTIDDLER=$$:/core/save/all

