  cui:
    build: ./  # 以当前的Dockerfile构建
    restart: always
    networks:
      bone:
    volumes:
      - dataVol:/var/lib/tiddlywiki
    environment:
      - TW_WIKIPATH=cui
      - TW_USERNAME=
      - TW_PASSWORD=
      ## double $ to escpae
      - TW_ROOTTIDDLER=$$:/core/save/all

