#!/bin/bash

#set -e

if [ ! -d /var/lib/tiddlywiki/${TW_WIKIPATH} ]; then
  tiddlywiki ${TW_WIKIPATH} --init server
fi

exec tiddlywiki ${TW_WIKIPATH} --server 8080 "${TW_ROOTTIDDLER}" text/plain text/html "${TW_USERNAME}" "${TW_PASSWORD}" 0.0.0.0
